// <auto-generated />
using System;
using ItemMaster.Infrastructure.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItemMaster.Infrastructure.Ef.Migrations
{
    [DbContext(typeof(ItemMasterDbContext))]
    partial class ItemMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ItemMaster.Infrastructure.Ef.ItemLogEntry", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                b.Property<string>("RequestId")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasAnnotation("MySql:CharSet", "utf8mb4");

                b.Property<string>("Sku")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasAnnotation("MySql:CharSet", "utf8mb4");

                b.Property<string>("Source")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasAnnotation("MySql:CharSet", "utf8mb4");

                b.Property<DateTime>("TimestampUtc")
                    .HasColumnType("datetime(6)");

                b.HasKey("Id");

                b.HasIndex("RequestId");

                b.ToTable("item_master_logs");
            });
#pragma warning restore 612, 618
        }
    }
}

