name: Integration Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

permissions:
  contents: read

env:
  AWS_REGION: ap-southeast-1
  LAMBDA_FUNCTION_NAME: im-dev-lambda-item-master
  MYSQL_SECRET_ID: ${{ secrets.RDS_SECRET_ID }}

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: item_master
          MYSQL_USER: im_user
          MYSQL_PASSWORD: im_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: sqs,secretsmanager
          DEBUG: 1
          DOCKER_HOST: unix:///var/run/docker.sock
        ports:
          - 4566:4566
        options: >-
          --health-cmd="curl -f http://localhost:4566/_localstack/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Configure AWS credentials for LocalStack
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: test
          aws-secret-access-key: test
          aws-region: ${{ env.AWS_REGION }}
        env:
          AWS_ENDPOINT_URL: http://localhost:4566
      
      - name: Create SQS queue
        run: |
          aws sqs create-queue \
            --queue-name im-dev-item-master-queue \
            --endpoint-url http://localhost:4566 \
            --region $AWS_REGION
      
      - name: Create secrets in LocalStack
        run: |
          aws secretsmanager create-secret \
            --name $MYSQL_SECRET_ID \
            --secret-string '{"username":"im_user","password":"im_pass","host":"mysql","port":3306,"database":"item_master"}' \
            --endpoint-url http://localhost:4566 \
            --region $AWS_REGION
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build integration tests
        run: dotnet build ItemMaster.Lambda/test/ItemMaster.Integration.Tests/ItemMaster.Integration.Tests.csproj --configuration Release
      
      - name: Apply database migrations
        run: |
          cd ItemMaster.Lambda/src/ItemMaster.Infrastructure
          dotnet ef database update \
            --startup-project ../ItemMaster.Lambda \
            --connection "Server=localhost;Database=item_master;User=im_user;Password=im_pass;"
      
      - name: Run integration tests
        run: |
          dotnet test ItemMaster.Lambda/test/ItemMaster.Integration.Tests/ItemMaster.Integration.Tests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=integration-results.trx" \
            --filter Category=Integration
      
      - name: Upload integration test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: integration-results.trx
          retention-days: 30
      
      - name: Generate summary
        if: always()
        run: |
          echo "## Integration Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Integration tests completed" >> $GITHUB_STEP_SUMMARY
          echo "Test results uploaded as artifacts" >> $GITHUB_STEP_SUMMARY
